Added Live Content shortcode
mt-support/tribe-ext-events-happening-now pull request #3
Opened 2020-04-07 02:36 UTC by rafsuntaskin

**[tribe-event-live-content]**  shortcode added to show content between the start and end times of the event only.

Example usage:
http://p.tri.be/cPeh3g

2020-05-18 22:45 UTC, cliffordp requested changes
Besides what's in my line-specific comments, you could convert these shortcodes to use Common's recent updates: https://github.com/moderntribe/tribe-common/blob/master/src/Tribe/Shortcode/Shortcode_Abstract.php

Example how-to: https://github.com/moderntribe/event-tickets-plus/tree/release/G20.05/src/Tribe/Shortcode

2020-05-18 22:45 UTC, cliffordp commented on src/Tribe/Live_Content.php
> +			return __( 'No Start Time is set for Live Content to appear.', 'tribe-ext-events-happening-now' );
consider changing to `_x(...)`

2020-05-18 22:45 UTC, cliffordp commented on readme.txt
> +
Add your changelog entry

2020-05-18 22:45 UTC, cliffordp commented on readme.txt
> +Stable tag: TBD
add your version

2020-05-18 22:45 UTC, cliffordp commented on src/views/happening-now.php
> + * @version TBD
when this template was added

2020-05-18 22:45 UTC, cliffordp commented on tribe-ext-events-happening-now.php
> + * Version:           TBD
your version number

2020-05-18 22:45 UTC, cliffordp commented on readme.txt
>  Tested up to: 5.3.2
update WP version

2020-05-18 22:45 UTC, cliffordp commented on readme.txt
Document the new `[tribe-event-live-content]`

2020-05-18 22:45 UTC, cliffordp commented on src/Tribe/Live_Content.php
> +		'end_time'         => [ self::class, 'validate_time_string' ],
are all 3 of these the same validation, especially `content_extended`?

2020-05-18 22:45 UTC, cliffordp commented on src/Tribe/Live_Content.php
> +		'id'               => [ self::class, 'validate_event' ],
Consider renaming from "event" to "post"

2020-05-18 22:45 UTC, cliffordp commented on src/Tribe/Live_Content.php
> +	}
Consider using `tribe_post_exists()`

If null, get current post. If not null, check if post exists - if it doesn't (bad ID passed), have the shortcode return an empty string.

2020-09-22 13:51 UTC, rafsuntaskin commented
I assume this is deprecated now. So, closing the PR to minimize noise for PRs.

2020-09-22 13:51 UTC, closed without merging